// ═══════════════════════════════════════════════════════════════════════════
// CHRONICLES OF AZURERUNE — game strings (EN). Loaded after data.js.
// The FULL 5-level story string table for the dragon port. English only.
// Tone: earnest heroic fantasy with a wry streak.
// ═══════════════════════════════════════════════════════════════════════════
'use strict';

Lang.strings = {
  en: {
    // ── UI ──
    title: 'Chronicles of Azurerune', subtitle: 'The Heroes’ Challenge',
    lvl1: 'Level 1: School Day', lvl2: 'Level 2: Kingfisher Festival', lvl3: 'Level 3: Library of Secrets',
    lvl4: 'Level 4: Yurthgreen Masquerade', lvl5: 'Level 5: When the Home Burns',
    enemies: 'Enemies', victory: 'Victory!', defeat: 'Defeat!', press_space: '[SPACE or CLICK]',
    paused: 'PAUSED', resume: 'Resume [ESC]', restart_act: 'Restart act [R]', quit_title: 'Quit to title [Q]',
    game_over: 'THE PARTY HAS FALLEN', retry_act: 'Retry this act [R]',
    hero_down: 'DOWN!', revived: 'REVIVED!', scrolls: 'Scrolls', hp_full: 'FULL',
    titan_form: 'TITAN FORM!', party_invisible: 'PARTY INVISIBLE!', cleave: 'CLEAVE!', barrage: 'BARRAGE!',
    freeze_shot: 'FREEZE SHOT!', bone_shot: 'BONE SHOT!', party_healed: 'PARTY HEALED!',
    ult_ready: '[X] Ultimate ready', ult_used: '[X] Ultimate used', air: 'AIR', survive: 'SURVIVE',
    fish_caught: 'Fish caught!', fish_missed: 'Missed!', fish_round: 'Round', muted: '[M] MUTED', music: '[M] music',
    the_end: 'THE END', credits: 'Chronicles of Azurerune — Book One Complete', press_any: 'Press SPACE for title',
    narrator: 'Narrator', tutorial: 'Tutorial', guard: 'Guard',
    // ── Speaker display names (engine renders d(speaker,key) via Lang.t(speaker)) ──
    kote: 'Kote', minerva: 'Minerva', elber: 'Elber', nesta: 'Nesta', nick: 'Nick',
    bakaris: 'Bakaris', Mayor: 'Mayor', Ispin: 'Ispin', ispin: 'Ispin', Kansaldi: 'Kansaldi',
    kansaldi: 'Kansaldi', lohezet: 'Lohezet', regent: 'Lord Regent', herald: 'Herald', becklin: 'Becklin',
    // ── NPC standing-label names (talkNPCs draws Lang.t(name)) ──
    npc_masked: '???', npc_levna: 'Levna', npc_clystran: 'Clystran', npc_becklin: 'Becklin',
    npc_cudgel: 'Cudgel', npc_tem: 'Tem Temble', npc_armory: 'Armory Master',
    // ═══════════ LEVEL 1 — SCHOOL DAY ═══════════
    l1a1_hint: 'Act 1: Final Exam — defeat Bakaris and his crew!',
    l1a1_1: 'Azurerune Fortress — the Tribunal watches from above.',
    l1a1_2: 'This is the final exam. Survive!',
    l1a1_tut: 'ARROWS/WASD move · Z attack · Q skill · K dash · X ultimate · TAB swap hero · ESC pause',
    l1a1_bak: '"You think you can beat me?"',
    l1a1_go: 'Defeat Bakaris and his crew to advance!',
    l1a1_win: 'Victory in the exam!',
    l1a2_1: 'The exam ends. Bakaris falls to one knee.',
    l1a2_2: 'You... you beat me...',
    l1a2_3: 'You hurt my familiar. You sealed your fate!',
    l1a2_4: 'Nesta draws a blade. Blood spills.',
    l1a2_5: 'Bakaris screams as a scar tears across his face.',
    l1a2_6: 'The tribunal above shifts uneasily.',
    l1a2_7: 'This was no simple exam anymore.',
    l1a3_hint: 'Act 3: Hallway Rumors — walk right; press Z near students to talk',
    l1a3_1: 'Azurerune corridors. Whispers of the exam echo.',
    l1a3_2: 'Talk to the other students. What do they know?',
    l1a3_levna1: 'That mark on Bakaris... I’ve seen something like it in my uncle’s bestiary.',
    l1a3_levna2: 'A spiral wound pattern. Like a talon that carries memory.',
    l1a3_levna3: 'Blue dragons leave marks that don’t fade. Not on skin, not on stone.',
    l1a3_levna4: 'Whatever Nesta did — she’s written herself into history whether she wanted to or not.',
    l1a3_cly1: 'Dragons are supposed to be extinct. The Cataclysm supposedly ended all of that.',
    l1a3_cly2: 'But that wound on Bakaris — I’ve studied metallurgy. No blade makes that spiral.',
    l1a3_cly3: 'Living things make spiral wounds. Something channeled through Nesta’s hand.',
    l1a3_cly4: 'I don’t know what it means. But I intend to find out.',
    l1a3_dar1: 'Did you see it? Bakaris went down like he’d been struck by lightning.',
    l1a3_dar2: 'A real knight fights for others. I don’t think Bakaris ever understood that.',
    l1a3_dar3: 'I want to serve someone who does. Someone like... well. Like all of you.',
    l1a3_dar4: 'If you ever need someone to carry your gear — I’m serious. Call on me.',
    l1a3_and1: 'The old gods watch this school more closely than its masters believe.',
    l1a3_and2: 'Bakaris comes from a powerful family. This wound to his pride will fester.',
    l1a3_and3: 'Pride is the wound that never heals without humility — and he has none.',
    l1a3_and4: 'I will pray for you. I think you have made an enemy who remembers.',
    l1a3_done: 'The truth becomes clearer with each step...',
    l1a4_hint: 'Act 4: Night Infiltration — avoid the Guard! Three platforms: pick your level!',
    l1a4_1: 'Under cover of night, the group sneaks into the library.',
    l1a4_2: 'A guard patrols and switches between three platforms.',
    l1a4_3: 'Stay on a platform the guard is NOT on. Jump up or drop down to dodge.',
    l1a4_4: 'Or press X as Nesta to turn the whole party invisible and walk right past.',
    l1a4_caught1: 'Intruder! The heroes flee...',
    l1a4_caught2: 'I see you! Sound the alarm!',
    l1a4_win: 'The library secrets are revealed!',
    l1a5_1: 'The library holds many secrets.',
    l1a5_2: 'The group gathers to discuss their findings.',
    l1a5_3: 'The Kingfisher Festival is in Vogler. Join us!',
    l1a5_4: 'Vogler: the trading hub of the realm.',
    l1a5_5: 'But first, they must understand the scar.',
    l1a5_6: 'A blue dragon. A connection. A journey begins.',
    l1a5_7: 'Next stop: Vogler.',
    // ═══════════ LEVEL 2 — KINGFISHER FESTIVAL ═══════════
    l2a1_hint: 'River Ambush: defeat the Darkmantles before your air runs out!',
    l2a1_1: 'On the river road to Vogler, the current drags the party under...',
    l2a1_2: 'Nesta stayed at the academy — her fox needs healing, and the Tribunal has questions. She’ll catch up.',
    l2a1_3: 'Suddenly, Darkmantles emerge from the darkness!',
    l2a1_4: 'Defeat them! Watch the AIR gauge — surface is sealed!',
    l2a1_win: 'The ambush is defeated!',
    l2a2_hint: 'Festival: explore Vogler and talk to the locals',
    l2a2_1: 'Vogler village — the festival center.',
    l2a2_2: 'Welcome, heroes! But darkness clouds our joy...',
    l2a2_3: 'The sabotage must be revealed!',
    l2a2_mayor: 'Welcome to Vogler village! Enjoy the Kingfisher Festival.',
    l2a2_ispin: 'The fishing competition awaits! Head east when you’re ready.',
    l2a2_done1: 'The fishing competition is about to start!',
    l2a2_done2: 'Head to the river — it’s time to fish!',
    l2a3_hint: 'Fishing Minigame: press SPACE when the marker is in the green zone — 3 catches to win',
    l2a3_1: 'The Kingfisher Fishing Competition begins!',
    l2a3_2: 'Time to prove your skills with the line.',
    l2a4_hint: 'Shadow on the Road: defeat the Draconian Kapak!',
    l2a4_1: 'Shadow on the Road...',
    l2a4_2: 'A Draconian Kapak blocks the path!',
    l2a4_3: 'Defeat it!',
    l2a4_win: 'The Draconian Kapak falls in acid!',
    // ═══════════ LEVEL 3 — LIBRARY OF SECRETS ═══════════
    l3a1_hint: 'Silence Threshold: slip past the Censor — use the upper path',
    l3a1_1: 'Inside the Library of Secrets...',
    l3a1_2: 'A Censor patrols the halls. Its guards watch the floor.',
    l3a1_3: 'Avoid detection and reach the far end!',
    l3a1_4: 'The censor patrols the middle. Take the upper balcony to slip through unseen.',
    l3a1_caught: 'Detected! Forced to retreat...',
    l3a1_caught2: 'The guard noticed you! Fall back!',
    l3a1_win: 'Stealth successful!',
    l3a2_hint: 'The Restricted Archive: climb to the top balcony!',
    l3a2_1: 'The forbidden knowledge is kept on the highest shelf, as always.',
    l3a2_2: 'Climb the bookshelf walls and platforms to the top balcony!',
    l3a2_win: 'You have reached the restricted archive.',
    l3a3_hint: 'Echoes of the Past: destroy the animated weapons!',
    l3a3_1: 'The chamber echoes with ancient magic...',
    l3a3_2: 'Swords move on their own!',
    l3a3_3: 'Destroy them all!',
    l3a3_win: 'The curse breaks!',
    l3a4_hint: 'Deceptions and Depths: defeat the Spectator!',
    l3a4_1: 'A figure floats above the abyss...',
    l3a4_2: 'The Spectator observes all who enter. It teleports when cornered!',
    l3a4_3: 'Defeat it!',
    l3a4_win: 'The Spectator falls!',
    l3a5_hint: 'Escape: reach the exit on the right!',
    l3a5_1: 'The exit corridor lies ahead.',
    l3a5_beck: 'You made it through the library. Impressive. Now run — before the Directors wake.',
    l3a5_win: 'You escaped the library!',
    // ═══════════ LEVEL 4 — YURTHGREEN MASQUERADE ═══════════
    l4a1_hint: 'The Yurthgreen Masquerade: mingle and talk (Z near guests)',
    l4a1_1: 'The Yurthgreen Masquerade begins...',
    l4a1_2: 'A grand celebration of heroes and legends. Nesta rejoins the party at last!',
    l4a1_bak: 'A masked noble watches you coldly. That scar under the mask... it’s Bakaris. He says nothing. Yet.',
    l4a1_levna: 'The destiny awaits us.',
    l4a1_cly: 'Our bonds are tested.',
    l4a1_beck: 'What lies ahead?',
    l4a1_cud: 'The choice is ours.',
    l4a1_tem: 'Magic flows through us all.',
    l4a1_done: 'Moving deeper into the masquerade...',
    l4a2_1: 'The great hall grows quiet. A herald calls Minerva forward.',
    l4a2_2: 'Minerva Amberfall. Step forward and kneel.',
    l4a2_3: 'I... yes, my lord.',
    l4a2_4: 'This armor was worn by Helena Starmantle, Knight of the Rose. She fell at Neraka.',
    l4a2_5: 'She named no successor. The armor has waited — for the one it would choose.',
    l4a2_6: 'Why me? I’m a scholar. I study things. I don’t...',
    l4a2_7: 'The knights of old understood that wisdom and courage are not opposites.',
    l4a2_8: 'The armor settles onto Minerva’s shoulders with a sound like a long-held breath released.',
    l4a2_9: 'Something ancient and patient has finally found its purpose.',
    l4a3_1: 'A masked figure peels away from the dancing crowd — unseen by all others.',
    l4a3_2: 'Nesta. The girl who scarred the unbeatable Bakaris.',
    l4a3_3: 'Who are you?',
    l4a3_4: 'Someone who recognizes power when she sees it. And power needs direction.',
    l4a3_5: 'The Dragon Armies are moving. Your little trick won’t be enough.',
    l4a3_6: 'I can teach you what the school won’t. Real shadow magic.',
    l4a3_7: 'At what cost?',
    l4a3_8: 'Your trust. And your silence. For now.',
    l4a3_9: 'I’ll think about it.',
    l4a3_10: 'Don’t think too long. Events move faster than most realize.',
    l4a3_prove: 'Prove yourself.',
    l4a3_hint: 'Defeat the shadow agents!',
    l4a3_win1: 'Impressive. The pact is sealed.',
    l4a3_win2: 'What have I agreed to...?',
    l4a4_1: 'Ispin draws the heroes into a private alcove behind a tapestry.',
    l4a4_2: 'I shouldn’t do this here. But I’ve run out of time to wait.',
    l4a4_3: 'These pearls belonged to my grandmother. She was a scryer — she saw paths.',
    l4a4_4: 'Ispin arranges the pearls in a circle on the floor. They begin to glow.',
    l4a4_5: 'I see... a woman. Standing in fire. She’s not afraid of it.',
    l4a4_6: 'Your mother, Kote. She was Solamnic. Did you know?',
    l4a4_7: 'She never told me. She never talked about where she came from.',
    l4a4_8: 'She was protecting you from what comes with that name. But that time is ending.',
    l4a4_9: 'The pearls dim. The vision fades. The moons shift overhead.',
    l4a4_10: 'Something has been set in motion that cannot be undone.',
    l4a5_1: 'The ritual fades...',
    l4a5_2: 'There is much we have learned.',
    l4a5_3: 'The Golden Museum holds secrets.',
    l4a5_4: 'There, you will find the answers you seek.',
    l4a5_5: 'The masquerade concludes.',
    l4a5_6: 'But the true test lies ahead...',
    // ═══════════ LEVEL 5 — WHEN THE HOME BURNS ═══════════
    l5a1_hint: 'Calm Before Storm: walk right to the reenactment field',
    l5a1_1: 'Vogler prepares a war reenactment for the festival’s end...',
    l5a1_2: 'When the home burns, all must rise.',
    l5a1_3: 'Walk forward to watch the actors take the field.',
    l5a1_npc: 'Arm yourselves. Something about these "actors" feels wrong.',
    l5a2_hint: 'Broken Illusion: the mercenaries attack!',
    l5a2_1: 'The actors reveal their true weapons!',
    l5a2_2: 'This is no illusion — this is a real raid!',
    l5a2_3: 'Defeat all soldiers!',
    l5a2_win: 'The soldiers fall!',
    l5a3_hint: 'The Red Ruin: draconians reinforce!',
    l5a3_1: 'The Red Ruin has come!',
    l5a3_2: 'You cannot stop us all!',
    l5a3_3: 'Defeat the draconians!',
    l5a3_win: 'The draconians retreat!',
    l5a4_hint: 'First Wave: Sivak Draconian boss!',
    l5a4_1: 'A towering Sivak Draconian lands, wings blocking the sun.',
    l5a4_2: 'It stomps the ground — keep your distance when it rears up!',
    l5a4_3: 'This foe is formidable!',
    l5a4_win: 'The Sivak falls!',
    l5a5_hint: 'Iron and Fire: the Boilerdrak awakes!',
    l5a5_1: 'From the flames, the Boilerdrak emerges!',
    l5a5_2: 'Its armor glows with terrible heat — it spits fire from afar!',
    l5a5_3: 'Stand firm!',
    l5a5_win: 'The Boilerdrak is vanquished!',
    l5a6_hint: 'Last Stand: the Ogre and the Goblin Chief!',
    l5a6_1: 'A towering Ogre appears, bearing a Goblin Chief on its back!',
    l5a6_2: 'The chief is untouchable while he rides — topple the Ogre first!',
    l5a6_3: 'Defeat them!',
    l5a6_fall: 'The Goblin Chief tumbles to the ground!',
    l5a6_win: 'The last defenders fall!',
    l5a7_hint: 'No Hope: SURVIVE the Dragon Commander!',
    l5a7_1: 'The ground shakes...',
    l5a7_2: 'Kansaldi, the Dragon Commander, emerges from the fire!',
    l5a7_3: 'Your struggle ends now!',
    l5a7_4: 'This battle cannot be won. Survive until you see an opening!',
    l5end_1: 'Becklin stands in the doorway as the walls ignite around her.',
    l5end_2: '"Don’t look back! Run — all of you! Run and don’t stop!"',
    l5end_3: '"Becklin — NO—"',
    l5end_4: '"We can’t leave her, we have to—"',
    l5end_5: '"I will hold the line. This is what I was made for."',
    l5end_6: 'Arturito charges into the inferno. Kansaldi turns from the fleeing heroes.',
    l5end_7: 'The heroes run through walls of fire, through collapsing stone, through choking smoke.',
    l5end_8: 'Behind them: a roar that shakes the earth. Then silence. Then nothing.',
    l5end_9: 'They emerge into cold night air, lungs burning, eyes streaming.',
    l5end_10: '"We lost them both."',
    l5end_11: '"We’re alive. They made sure of that."',
    l5end_12: 'Vogler village. Dawn. The survivors count what they’ve saved and what they’ve lost.',
    l5end_13: 'Chronicles of Azurerune. Book One: Complete.',
  },
};
Lang.current = 'en';
